# This workflow will generate a JavaDoc for the project and publish it to GitHub pages
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Javadoc Generator

on:
  push:
    branches: [ main ]

jobs:
  javadoc-gen:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Generate JavaDoc
      run: ./gradlew javadoc

    - name: Deploy to pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        #token: ${{ inputs.GITHUB_TOKEN }}
        #branch: javadoc
        #clean: true
        folder: ./build/docs/javadoc
        #target-folder: ./build/docs/javadoc
