# This workflow will generate a JavaDoc for the project WITHOUT publishing
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Javadoc Generator

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  javadoc-gen:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Generate JavaDoc
      run: ./gradlew javadoc