# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Javadoc Generator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate JavaDoc
      run: javadoc -protected -splitindex -use -author -version -d ./docs

    - name: Deploy to pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        branch: javadoc
        clean: true
        folder: Library
        target-folder: ./docs
